### ISSUE TITLE
Add DWoC as open source event

### ISSUE THREAD

**Issue by PinRathod** [Khushi0321/Digital_Hospital#37]
This project is part of DWoC open source event.it should be mention in README file.

**Comment by PinRathod** [comment]
Can I work on this?

**Comment by Sloth-Panda** [comment]
would like to work on this

**Comment by Sloth-Panda** [comment]
@Khushi0321 can you add tags to this one ?

**Comment by PinRathod** [comment]
@Khushi0321 What are you doing? First of all I raised this issue and I asked for work on it.. after that @Sloth-Panda also asked and without assignment @Sloth-Panda make PR and you @Khushi0321 merged it. This is very bad for open source community. I raised issue, so first of all I have to work on it and also without assignment how can any one make PR for that issue which is not even raised by that person. Please,look into this matter. I hope you will do need full for the same. Ok

**Comment by Sloth-Panda** [comment]
@PinRathod  Hey bro, there was a previous issue if you can see and that was about readme updation and there is no meaning in opening another issue which comes inside readme updation only. As this issue was a small part of that and unnecessary to get raised I have to link this issue to that pr. Hope you get it.

**Comment by PinRathod** [comment]
@Sloth-Panda If there was a previous issue related to readme updation, I don't bother for that. This issue is not assigned for anyone. So, you must have to wait for the assignment. But, you took the issue and make PR for that.
